//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyLocalization
{
    using System;
    using UnityEngine;
    
    
    [System.SerializableAttribute()]
    public class LocalizationData
    {
        
        public int id;
        
        public string zh;//  ÖĞÎÄ
        public string cht;// ·±ÌåÖĞÎÄ
        public string en;//  Ó¢Óï
        public string spa;// Î÷°àÑÀÓï
        public string jp;//  ÈÕÓï
        public string pt;//  ÆÏÌÑÑÀÓï
        public string fra;// ·¨Óï
        public string kor;// º«Óï
        public string ru;//  ¶íÓï

        public string yue;// ÔÁÓï
        public string wyw;// ÎÄÑÔÎÄ

        public string th;// Ì©Óï
        public string ara;// °¢À­²®Óï
        public string de;// µÂÓï
        public string it;//  Òâ´óÀûÓï
        public string el;//  Ï£À°Óï
        public string nl;//  ºÉÀ¼Óï
        public string pl;// ²¨À¼Óï
        public string bul;// ±£¼ÓÀûÑÇÓï
        public string est;// °®É³ÄáÑÇÓï
        public string dan;// µ¤ÂóÓï
        public string fin;// ·ÒÀ¼Óï
        public string cs;// ½İ¿ËÓï
        public string rom;// ÂŞÂíÄáÑÇÓï
        public string slo;// Ë¹ÂåÎÄÄáÑÇÓï
        public string swe;// ÈğµäÓï
        public string hu;// ĞÙÑÀÀûÓï
        public string vie;// Ô½ÄÏÓï

        //±ÜÃâ·´Éä
        public string GetValue(string language)
        {
            switch(language)
            {
                case "zh"://  ÖĞÎÄ
                    return this.zh;
                case "cht":// ·±ÌåÖĞÎÄ
                    return this.cht;
                case "en"://  Ó¢Óï
                    return this.en;
                case "spa":// Î÷°àÑÀÓï
                    return this.spa;
                case "jp"://  ÈÕÓï
                    return this.jp;
                case "pt"://  ÆÏÌÑÑÀÓï
                    return this.pt;
                case "fra":// ·¨Óï
                    return this.fra;
                case "kor":// º«Óï
                    return this.kor;
                case "ru"://  ¶íÓï
                    return this.ru;

                case "yue":// ÔÁÓï
                    return this.yue;
                case "wyw":// ÎÄÑÔÎÄ
                    return this.wyw;

                case "th":// Ì©Óï
                    return this.th;
                case "ara":// °¢À­²®Óï
                    return this.ara;
                case "de":// µÂÓï
                    return this.de;
                case "it"://  Òâ´óÀûÓï
                    return this.it;
                case "el"://  Ï£À°Óï
                    return this.el;
                case "nl"://  ºÉÀ¼Óï
                    return this.nl;
                case "pl":// ²¨À¼Óï
                    return this.pl;
                case "bul":// ±£¼ÓÀûÑÇÓï
                    return this.bul;
                case "est":// °®É³ÄáÑÇÓï
                    return this.est;
                case "dan":// µ¤ÂóÓï
                    return this.dan;
                case "fin":// ·ÒÀ¼Óï
                    return this.fin;
                case "cs":// ½İ¿ËÓï
                    return this.cs;
                case "rom":// ÂŞÂíÄáÑÇÓï
                    return this.rom;
                case "slo":// Ë¹ÂåÎÄÄáÑÇÓï
                    return this.slo;
                case "swe":// ÈğµäÓï
                    return this.swe;
                case "hu":// ĞÙÑÀÀûÓï
                    return this.hu;
                case "vie":// Ô½ÄÏÓï 
                    return this.vie;
                default:
                    return string.Empty;
            }
        }

        public void SetValue(string language, string text)
        {
            switch (language)
            {
                case "zh"://  ÖĞÎÄ
                    this.zh = text;
                    break;
                case "cht":// ·±ÌåÖĞÎÄ
                    this.cht = text;
                    break;
                case "en"://  Ó¢Óï
                    this.en = text;
                    break;
                case "spa":// Î÷°àÑÀÓï
                    this.spa = text;
                    break;
                case "jp"://  ÈÕÓï
                    this.jp = text;
                    break;
                case "pt"://  ÆÏÌÑÑÀÓï
                    this.pt = text;
                    break;
                case "fra":// ·¨Óï
                    this.fra = text;
                    break;
                case "kor":// º«Óï
                    this.kor = text;
                    break;
                case "ru"://  ¶íÓï
                    this.ru = text;
                    break;

                case "yue":// ÔÁÓï
                    this.yue = text;
                    break;
                case "wyw":// ÎÄÑÔÎÄ
                    this.wyw = text;
                    break;

                case "th":// Ì©Óï
                    this.th = text;
                    break;
                case "ara":// °¢À­²®Óï
                    this.ara = text;
                    break;
                case "de":// µÂÓï
                    this.de = text;
                    break;
                case "it"://  Òâ´óÀûÓï
                    this.it = text;
                    break;
                case "el"://  Ï£À°Óï
                    this.el = text;
                    break;
                case "nl"://  ºÉÀ¼Óï
                    this.nl = text;
                    break;
                case "pl":// ²¨À¼Óï
                    this.pl = text;
                    break;
                case "bul":// ±£¼ÓÀûÑÇÓï
                    this.bul = text;
                    break;
                case "est":// °®É³ÄáÑÇÓï
                    this.est = text;
                    break;
                case "dan":// µ¤ÂóÓï
                    this.dan = text;
                    break;
                case "fin":// ·ÒÀ¼Óï
                    this.fin = text;
                    break;
                case "cs":// ½İ¿ËÓï
                    this.cs = text;
                    break;
                case "rom":// ÂŞÂíÄáÑÇÓï
                    this.rom = text;
                    break;
                case "slo":// Ë¹ÂåÎÄÄáÑÇÓï
                    this.slo = text;
                    break;
                case "swe":// ÈğµäÓï
                    this.swe = text;
                    break;
                case "hu":// ĞÙÑÀÀûÓï
                    this.hu = text;
                    break;
                case "vie":// Ô½ÄÏÓï 
                    this.vie = text;
                    break;
                default:
                    break;
            }
        }
    }
}
